let session = JSON.parse(localStorage.getItem('medilinkSession') || 'null');
const api = async (url, options={}) => { const headers = options.body instanceof FormData ? {} : {'Content-Type':'application/json'}; if(session?.token) headers.Authorization=`Bearer ${session.token}`; let r; try { r=await fetch(url,{...options,headers:{...headers,...options.headers}}); } catch { throw new Error('Server is temporarily unreachable. Please try again in a minute.'); } const raw=await r.text(); let d={}; try { d=raw ? JSON.parse(raw) : {}; } catch { throw new Error(`Server is temporarily unavailable (HTTP ${r.status}). Please try again shortly.`); } if(!r.ok) throw new Error(d.message||`Request failed (HTTP ${r.status})`); return d; };
const message = text => `<p class="form-message">${text}</p>`;
function closeModal(){document.querySelector('#modal').classList.remove('show')}
function openModal(content){document.querySelector('#modalContent').innerHTML=content;document.querySelector('#modal').classList.add('show')}
function openAuth(role='customer'){openModal(`<p class="eyebrow">WELCOME TO MEDILINK</p><h2>${role==='admin'?'Admin ':''}Account</h2><div class="tabs"><button onclick="authView('login','${role}')">Log in</button><button onclick="authView('register','${role}')">Create account</button></div><div id="authForm"></div>`);authView('login',role)}
function authView(kind,role){const box=document.querySelector('#authForm');if(kind==='login')box.innerHTML=`<form onsubmit="login(event)"><input name="email" type="email" placeholder="Email address" required><input name="password" type="password" placeholder="Password" required><button class="primary-btn">Log in</button><p class="hint">Use a ${role} account to access its portal.</p></form>`;else box.innerHTML=`<form onsubmit="register(event)"><input name="fullName" placeholder="Full name" required><input name="email" type="email" placeholder="Email address" required><input name="phone" placeholder="Phone number"><input name="password" type="password" placeholder="Password (min. 6 chars)" minlength="6" required><select name="role"><option value="customer" ${role==='customer'?'selected':''}>Customer</option><option value="pharmacist" ${role==='pharmacist'?'selected':''}>Pharmacist</option></select><button class="primary-btn">Create account</button></form>`}
async function register(e){e.preventDefault();try{const x=Object.fromEntries(new FormData(e.target));const d=await api('/api/auth/register',{method:'POST',body:JSON.stringify(x)});e.target.insertAdjacentHTML('afterend',message(d.message));}catch(err){alert(err.message)}}
async function login(e){e.preventDefault();try{session=await api('/api/auth/login',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});localStorage.setItem('medilinkSession',JSON.stringify(session));closeModal();updateNav();openPortal();}catch(err){alert(err.message)}}
function logout(){localStorage.removeItem('medilinkSession');session=null;document.querySelector('#appPanel').classList.add('hidden');document.querySelector('main').classList.remove('hidden');updateNav()}
function updateNav(){document.querySelector('#navAccount').innerHTML=session?`<button class="user-btn" onclick="openPortal()">${session.user.fullName}</button><button class="outline-btn" onclick="logout()">Log out</button>`:`<button class="outline-btn" onclick="openAuth()">Log in</button>`}
document.querySelector('#searchForm').addEventListener('submit',async e=>{e.preventDefault();const q=medicineInput.value;results.innerHTML='<p class="empty">Searching...</p>';try{const rows=await api(`/api/medicines/search?q=${encodeURIComponent(q)}`);results.innerHTML=rows.length?rows.map(x=>`<article class="result-item"><div class="result-info"><b>${x.brand_name}</b><p>${x.generic_name||'Medicine'} · ${x.pharmacy}, ${x.area||x.address}</p><small>৳ ${x.unit_price} · ${x.stock_qty} in stock</small></div><button class="primary-btn" onclick='reserve(${JSON.stringify(x)})'>Reserve</button></article>`).join(''):'<p class="empty">No approved pharmacy currently has this medicine. You can send an emergency request.</p>'}catch(err){results.innerHTML=`<p class="empty">Database unavailable: ${err.message}</p>`}});
document.querySelectorAll('.quick-search button').forEach(b=>b.onclick=()=>{medicineInput.value=b.textContent;document.querySelector('#searchForm').requestSubmit()});
function reserve(x){if(!session){openAuth('customer');return}if(session.user.role!=='customer'){alert('Please use a customer account to reserve medicine.');return}openModal(`<p class="eyebrow">ADVANCE RESERVATION</p><h2>${x.brand_name}</h2><p>${x.pharmacy}</p><form onsubmit='submitReservation(event,${x.id},${x.pharmacy_id})'><input name="quantity" type="number" min="1" max="${x.stock_qty}" value="1" required><button class="primary-btn">Confirm reservation</button></form>`)}
async function submitReservation(e,medicineId,pharmacyId){e.preventDefault();try{const d=await api('/api/reservations',{method:'POST',body:JSON.stringify({medicineId,pharmacyId,quantity:e.target.quantity.value})});e.target.insertAdjacentHTML('afterend',message(`${d.message}. Your pickup code: ${d.pickupCode}`));}catch(err){alert(err.message)}}
function openEmergency(){if(!session){openAuth('customer');return}openModal(`<p class="eyebrow">EMERGENCY REQUEST</p><h2>Need medicine urgently?</h2><form onsubmit="sendEmergency(event)"><input name="medicineName" placeholder="Medicine name" required><input name="area" placeholder="Your area"><textarea name="message" placeholder="Optional note"></textarea><button class="primary-btn">Send request</button></form>`)}
async function sendEmergency(e){e.preventDefault();try{const d=await api('/api/emergency-requests',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});e.target.insertAdjacentHTML('afterend',message(d.message));}catch(err){alert(err.message)}}
async function openPortal(){if(!session)return;document.querySelector('main').classList.add('hidden');const panel=document.querySelector('#appPanel');panel.classList.remove('hidden');panel.innerHTML='<p class="empty">Loading your workspace...</p>';try{if(session.user.role==='customer')return customerPortal(panel);if(session.user.role==='pharmacist')return pharmacistPortal(panel);return adminPortal(panel)}catch(err){panel.innerHTML=`<div class="dashboard"><h2>Unable to load portal</h2><p>${err.message}</p></div>`}}
async function customerPortal(panel){const r=await api('/api/reservations/my');panel.innerHTML=`<div class="dashboard"><p class="eyebrow">CUSTOMER PORTAL</p><h2>Hello, ${session.user.fullName}</h2><div class="portal-actions"><button class="primary-btn" onclick="document.querySelector('#search').scrollIntoView();document.querySelector('main').classList.remove('hidden');document.querySelector('#appPanel').classList.add('hidden')">Search medicine</button><button class="outline-btn" onclick="openEmergency()">Emergency request</button><button class="outline-btn" onclick="uploadPrescription()">Upload prescription</button></div><h3>My reservations</h3>${r.length?`<div class="table-wrap"><table><thead><tr><th>Medicine</th><th>Pharmacy</th><th>Quantity</th><th>Pickup code</th><th>Status</th></tr></thead><tbody>${r.map(x=>`<tr><td>${x.brand_name}</td><td>${x.pharmacy}</td><td>${x.quantity}</td><td><b>${x.pickup_code}</b></td><td>${x.status}</td></tr>`).join('')}</tbody></table></div>`:'<p class="empty">No reservations yet.</p>'}</div>`}
function uploadPrescription(){openModal(`<p class="eyebrow">PRESCRIPTION</p><h2>Upload prescription</h2><form onsubmit="sendPrescription(event)" enctype="multipart/form-data"><input type="file" name="prescription" accept="image/*,.pdf" required><textarea name="note" placeholder="Optional note for pharmacist"></textarea><button class="primary-btn">Upload securely</button></form>`)}
async function sendPrescription(e){e.preventDefault();try{const d=await api('/api/prescriptions',{method:'POST',body:new FormData(e.target)});e.target.insertAdjacentHTML('afterend',message(d.message));}catch(err){alert(err.message)}}
async function pharmacistPortal(panel){const d=await api('/api/pharmacy/dashboard');if(d.needsPharmacy){panel.innerHTML=`<div class="dashboard"><p class="eyebrow">PHARMACIST PORTAL</p><h2>Add your pharmacy</h2><form class="inline-form" onsubmit="createPharmacy(event)"><input name="name" placeholder="Pharmacy name" required><input name="address" placeholder="Full address" required><input name="area" placeholder="Area"><input name="phone" placeholder="Phone"><button class="primary-btn">Submit for approval</button></form></div>`;return}const s=d.summary;panel.innerHTML=`<div class="dashboard"><p class="eyebrow">PHARMACY PORTAL</p><h2>Inventory dashboard</h2><div class="stats"><div><span>Today's sales</span><b>৳ ${s.salesToday}</b></div><div><span>Medicines</span><b>${s.medicines}</b></div><div><span>Low stock</span><b class="warning">${s.lowStock}</b></div><div><span>Expiring in 30 days</span><b class="danger">${s.expiring}</b></div></div><div class="portal-actions"><button class="primary-btn" onclick="addMedicine()">+ Add medicine</button></div><h3>Inventory & alerts</h3><div class="table-wrap"><table><thead><tr><th>Medicine</th><th>Stock</th><th>Price</th><th>Expiry</th><th>Alert</th></tr></thead><tbody>${d.items.map(x=>`<tr><td><b>${x.brand_name}</b><br><small>${x.generic_name||''}</small></td><td>${x.stock_qty}</td><td>৳ ${x.unit_price}</td><td>${x.expiry_date||'-'}</td><td>${x.stock_qty<=x.low_stock_level?'Low stock':''}</td></tr>`).join('')}</tbody></table></div><h3>Pending reservations</h3>${d.reservations.length?d.reservations.map(x=>`<p class="notice"><b>${x.brand_name}</b> × ${x.quantity} — ${x.full_name} — code: ${x.pickup_code}</p>`).join(''):'<p class="empty">No pending reservations.</p>'}</div>`}
async function createPharmacy(e){e.preventDefault();try{const d=await api('/api/pharmacies',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});alert(d.message)}catch(err){alert(err.message)}}
function addMedicine(){openModal(`<p class="eyebrow">INVENTORY</p><h2>Add medicine</h2><form onsubmit="saveMedicine(event)"><input name="brandName" placeholder="Brand name" required><input name="genericName" placeholder="Generic name"><input name="category" placeholder="Category"><input name="unitPrice" type="number" step="0.01" placeholder="Unit price" required><input name="stockQty" type="number" placeholder="Current stock" required><input name="lowStockLevel" type="number" value="10" placeholder="Low stock alert level"><input name="expiryDate" type="date"><button class="primary-btn">Save medicine</button></form>`)}
async function saveMedicine(e){e.preventDefault();try{const d=await api('/api/medicines',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});closeModal();alert(d.message);openPortal()}catch(err){alert(err.message)}}
async function adminPortal(panel){const d=await api('/api/admin/overview');panel.innerHTML=`<div class="dashboard"><p class="eyebrow">ADMIN PORTAL</p><h2>Platform overview</h2><div class="stats"><div><span>Users</span><b>${d.data.users}</b></div><div><span>Approved pharmacies</span><b>${d.data.pharmacies}</b></div><div><span>Medicine records</span><b>${d.data.medicines}</b></div><div><span>Open emergencies</span><b class="danger">${d.data.emergencies}</b></div></div><h3>Pharmacy onboarding</h3>${d.pending.length?d.pending.map(x=>`<p class="notice"><b>${x.name}</b> — ${x.address} <button class="primary-btn small" onclick="approve(${x.id})">Approve</button></p>`).join(''):'<p class="empty">No pharmacies waiting for approval.</p>'}</div>`}
async function approve(id){try{await api(`/api/admin/pharmacies/${id}/approve`,{method:'PATCH'});openPortal()}catch(err){alert(err.message)}}
updateNav();
